include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FrontCamAsBackPreferences

FrontCamAsBackPreferences_FILES = FrontCamAsBackRootListController.m
FrontCamAsBackPreferences_FRAMEWORKS = UIKit
FrontCamAsBackPreferences_PRIVATE_FRAMEWORKS = Preferences
FrontCamAsBackPreferences_INSTALL_PATH = /Library/PreferenceBundles
FrontCamAsBackPreferences_BUNDLE_EXTENSION = plist

include $(THEOS_MAKE_PATH)/bundle.mk
